runtime: nodejs18

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  CS_DISCORD_TOKEN: "CS_DISCORD_TOKEN_PLACEHOLDER"
  CS_WELCOME_MESSAGE_URL: "CS_WELCOME_MESSAGE_URL_PLACEHOLDER"